version: '3'
services:
  datastore:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_DATA_DIR=/usr/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ../data/db:/usr/data/db
  webapp:
    build: .
    ports:
      - 81:8081
    environment:
      - DB=mongodb://datastore:27017/data
    volumes:
      - .:/data
    links:
      - datastore


  